# Generated by Django 4.2.7 on 2023-12-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
    ]
